name: Hourly Python script run to replace table json
on:
  workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: 'Log level'     
    #     required: true
    #     default: 'warning'
    #   tags:
    #     description: 'Test scenario tags'  
    #   environment:
    #     type: environment
    #     description: Select the environment
    #     default: "tspdt-tmdb"
  schedule:
    - cron: "0 * * * *"
  repository_dispatch:

env:
  VITE_PUBLIC_KEY: ${{ secrets.VITE_PUBLIC_KEY }}
  VITE_TEMPLATE_ID: ${{ secrets.VITE_TEMPLATE_ID }}
  VITE_SERVICE_ID: ${{ secrets.VITE_SERVICE_ID }}
  VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
jobs:
  python-script:
    environment:
      name: tspdt-tmdb
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./utils/requirements.txt
      - name: Check out the repository to the runner
        uses: actions/checkout@v5
      - name: Run Python script
        env:
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: |
          git config user.email github-actions
          git config user.name github-actions@github.com
          git pull
          git push
          python ./utils/providers.py
          git add .
          git commit -m "New json"
          git push

  build_and_preview:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TSPDT_TMDB }}
          projectId: tspdt-tmdb
          channelId: live
